/*
 * Fixture mode only: choose which generated scenario each endpoint answers
 * with, so every `10` §8 state can be shown on the phone without a code
 * change (TC-MOBILE-STATE-001). The scenario names are the generator's
 * (contracts/api/generate_fixture.py), listed from the bundle - nothing
 * here invents a response.
 *
 * Tap a row to cycle that endpoint through its scenarios. The open screen
 * re-mounts and re-fetches after every change.
 */

import React, { useEffect, useState } from 'react';
import { FlatList, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

import { color, font, MIN_TOUCH, space } from './theme';

export default function FixtureScenarioPanel({ visible, onClose, overrides }) {
  const [, setTick] = useState(0);
  useEffect(() => (overrides ? overrides.subscribe(() => setTick((n) => n + 1)) : undefined), [overrides]);
  if (!overrides) return null;

  const rows = overrides.endpoints()
    .map((id) => ({ id, names: overrides.scenariosFor(id), current: overrides.get(id) }))
    .filter((r) => r.names.length > 1);

  const cycle = (row) => {
    const i = row.names.indexOf(row.current);
    overrides.set(row.id, row.names[(i + 1) % row.names.length]);
  };

  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose} transparent={false}>
      <View style={s.root}>
        <Text style={s.h1}>Fixture scenarios</Text>
        <Text style={s.note}>
          Generated by contracts/api/generate_fixture.py. Tap an endpoint to cycle its scenario; the open screen
          reloads. Live builds have no such panel.
        </Text>
        <FlatList
          data={rows}
          keyExtractor={(r) => r.id}
          renderItem={({ item }) => (
            <TouchableOpacity style={s.row} onPress={() => cycle(item)} accessibilityRole="button">
              <Text style={s.endpoint}>{item.id}</Text>
              <Text style={[s.scenario, item.current !== 'default' && s.changed]}>{item.current}</Text>
            </TouchableOpacity>
          )}
        />
        <View style={s.actions}>
          <TouchableOpacity style={s.btn} onPress={() => overrides.clear()} accessibilityRole="button">
            <Text style={s.btnT}>All default</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[s.btn, s.btnP]} onPress={onClose} accessibilityRole="button">
            <Text style={s.btnT}>Close</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: color.bg, padding: space.l, paddingTop: 48 },
  h1: { color: color.text, fontSize: font.h1, fontWeight: '700' },
  note: { color: color.textDim, fontSize: font.small, marginVertical: space.s },
  row: {
    minHeight: MIN_TOUCH, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    borderBottomWidth: 1, borderBottomColor: color.border, paddingHorizontal: space.s,
  },
  endpoint: { color: color.text, fontFamily: font.mono, fontSize: font.small, flex: 1 },
  scenario: { color: color.textDim, fontFamily: font.mono, fontSize: font.small },
  changed: { color: color.warn, fontWeight: '700' },
  actions: { flexDirection: 'row', gap: space.s, marginTop: space.m, marginBottom: space.xl },
  btn: {
    flex: 1, minHeight: MIN_TOUCH, borderRadius: 8, borderWidth: 1, borderColor: color.border,
    alignItems: 'center', justifyContent: 'center', backgroundColor: color.surfaceHi,
  },
  btnP: { borderColor: color.accent, backgroundColor: color.accentBg },
  btnT: { color: color.text, fontSize: font.body, fontWeight: '600' },
});
