#!/usr/bin/env python3
"""
Stage the S-1 device assets: page bundle, real-mesh levels, B6 targets, 2D mask slices.

THROWAWAY SPIKE CODE under spikes/spike_b_3d/. Day 22 (2026-10-01), Claude agent under
the leader's recovery override; Spike B owner Vu Hung Anh adopts or rejects on Day 23.

    python spikes/spike_b_3d/harness/real_mesh_frontier.py      # writes the meshes first
    python spikes/spike_b_3d/s1/stage_assets.py                 # then this

Everything written here is derived from a patient mask, so the output folder is a NEW
gitignored spikes/spike_b_3d/mesh/out_real/s1_assets/<timestamp>/spike_b_s1/ per run (nothing
is ever deleted; LATEST.txt names the newest). build_release.ps1 copies it into the APK as
android/app/src/main/assets/spike_b_s1/; it lives only there and here.

What it writes, and why each piece exists:
  meshes/level_<i>_cell<c>.obj  the SAME files the offline B5 harness measured; every
                                SHA-256 is checked against mesh_levels_real.json first
  s1_manifest.json              geometry, levels, B6 targets, slice-image crop
  slices/slice_<zzz>.png        one image per source slice of the MASK (no MRI pixels),
                                shown by the React Native 2D panel for B7
  index.html, s1_bundle.js      the page: one classic script, because ES modules do not
                                load over file:// in the Android WebView
  stage_record.json             SHA-256 of every staged file, for the build record

B6 TARGETS. Face centres on the level-0 surface (= the mask's own boundary faces),
stratified by slice band and face orientation, chosen deterministically. Each carries the
slice of the foreground voxel that owns the face (`expected_slice`). Note what the device
will do with a +z cap: the face of slice k lies at z = k+1, so a floor pick returns k+1 -
error 1, inside the bound; the extractor scores every pick against the mask along the
logged ray anyway, which is the primary B6 number.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import zlib

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(ROOT))
sys.path.insert(0, os.path.join(ROOT, "harness"))
sys.path.insert(0, os.path.join(ROOT, "mesh"))

from real_mesh_frontier import DEFAULT_DATA_ROOT, DEFAULT_DATASET_MANIFEST, load_mask, sha256_file  # noqa: E402

DEFAULT_CASE = "CASE_0059"
DEFAULT_ASSET_ROOT = os.path.join(ROOT, "mesh", "out_real", "s1_assets")   # + /<stamp>/spike_b_s1
BUNDLE_SOURCES = [
    os.path.join(ROOT, "app", "picking.js"),
    os.path.join(HERE, "frame_probe_pr44.js"),
    os.path.join(ROOT, "app", "obj.js"),
    os.path.join(HERE, "s1_core.js"),
    os.path.join(HERE, "s1_viewer.js"),
]
BANDS = 6
SIDE_PER_BAND = 4
CAP_PER_BAND = 2
SLICE_MARGIN = 16


def bundle_js(sources) -> str:
    """Concatenate ES modules into one classic script: drop imports, strip `export `."""
    parts = ["/* GENERATED by spikes/spike_b_3d/s1/stage_assets.py - do not edit. */",
             "(function () {", "'use strict';"]
    for path in sources:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        text = re.sub(r"^\s*import\s[^;]*?from\s+['\"][^'\"]+['\"];\s*$", "", text, flags=re.M | re.S)
        text = re.sub(r"^export\s+(?=(const|let|function|class|async)\b)", "", text, flags=re.M)
        if re.search(r"^\s*(import|export)\b", text, flags=re.M):
            raise SystemExit(f"{path}: an import/export survived bundling; keep them on one line")
        parts.append(f"/* ---- {os.path.relpath(path, ROOT).replace(os.sep, '/')} ---- */")
        parts.append(text)
    parts.append("})();")
    return "\n".join(parts) + "\n"


def png_gray(path, img: np.ndarray) -> None:
    """Minimal 8-bit grayscale PNG writer (zlib only)."""
    h, w = img.shape
    raw = b"".join(b"\x00" + img[r].astype(np.uint8).tobytes() for r in range(h))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    with open(path, "wb") as fh:
        fh.write(b"\x89PNG\r\n\x1a\n")
        fh.write(chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 0, 0, 0, 0)))
        fh.write(chunk(b"IDAT", zlib.compress(raw, 9)))
        fh.write(chunk(b"IEND", b""))


def boundary_faces(mask: np.ndarray):
    """(x, y, z, axis, sign) for every face between a foreground voxel and background."""
    fg = mask > 0
    out = []
    for axis in range(3):
        for sign in (-1, 1):
            nb = np.zeros_like(fg)
            src = [slice(None)] * 3
            dst = [slice(None)] * 3
            if sign > 0:
                src[axis], dst[axis] = slice(1, None), slice(None, -1)
            else:
                src[axis], dst[axis] = slice(None, -1), slice(1, None)
            nb[tuple(dst)] = fg[tuple(src)]          # nb[v] = fg[v + sign * e_axis]
            faces = np.argwhere(fg & ~nb)
            for x, y, z in faces:
                out.append((int(x), int(y), int(z), axis, sign))
    return out


def choose_targets(mask, spacing, origin):
    faces = boundary_faces(mask)
    zs = np.array([f[2] for f in faces])
    zlo, zhi = int(zs.min()), int(zs.max())
    edges = np.linspace(zlo, zhi + 1, BANDS + 1)
    targets = []
    for b in range(BANDS):
        in_band = [f for f in faces if edges[b] <= f[2] < edges[b + 1]]
        for group, want in (("side", SIDE_PER_BAND), ("cap", CAP_PER_BAND)):
            cands = sorted((f for f in in_band if (f[3] == 2) == (group == "cap")),
                           key=lambda f: (f[2], f[3], f[4], f[0], f[1]))
            if not cands:
                continue
            idx = np.linspace(0, len(cands) - 1, want + 2)[1:-1].round().astype(int)
            for i in sorted(set(idx.tolist())):
                x, y, z, axis, sign = cands[i]
                c = [x + 0.5, y + 0.5, z + 0.5]
                c[axis] = (x, y, z)[axis] + (1 if sign > 0 else 0)
                world = [origin[k] + c[k] * spacing[k] for k in range(3)]
                targets.append({
                    "id": f"T{len(targets):02d}",
                    "world": [round(v, 6) for v in world],
                    "expected_slice": z,
                    "face": f"{'+' if sign > 0 else '-'}{'xyz'[axis]}",
                    "owner_voxel": [x, y, z],
                    "band": b,
                })
    return targets, {"bands": BANDS, "z_range": [zlo, zhi], "side_per_band": SIDE_PER_BAND,
                     "cap_per_band": CAP_PER_BAND, "boundary_faces": len(faces)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case-id", default=DEFAULT_CASE)
    ap.add_argument("--mesh-dir", help="default: mesh/out_real/<case_id>")
    ap.add_argument("--data-root", default=DEFAULT_DATA_ROOT)
    ap.add_argument("--dataset-manifest", default=DEFAULT_DATASET_MANIFEST)
    ap.add_argument("--out", help="default: mesh/out_real/s1_assets/<timestamp>/spike_b_s1 (new folder)")
    args = ap.parse_args()

    mesh_dir = args.mesh_dir or os.path.join(ROOT, "mesh", "out_real", args.case_id)
    stamp = dt.datetime.now().strftime("%Y%m%dT%H%M%S")
    out = os.path.abspath(args.out or os.path.join(DEFAULT_ASSET_ROOT, stamp, "spike_b_s1"))
    try:
        inside_repo = os.path.commonpath([out, REPO]) == REPO
    except ValueError:
        inside_repo = False
    probe = subprocess.run(["git", "-C", REPO, "check-ignore", "-q", os.path.join(out, "x.obj")])
    if inside_repo and probe.returncode != 0:
        raise SystemExit(f"{out} is not gitignored; staged assets are derived from a real mask")
    if os.path.exists(out):
        # Never delete: every staging run gets a fresh folder.
        raise SystemExit(f"{out} already exists; pass a new --out (nothing is deleted here)")

    with open(os.path.join(mesh_dir, "mesh_levels_real.json"), encoding="utf-8") as fh:
        index = json.load(fh)
    if index["case_id"] != args.case_id:
        raise SystemExit(f"mesh_levels_real.json is for {index['case_id']}, not {args.case_id}")

    os.makedirs(os.path.join(out, "meshes"))
    os.makedirs(os.path.join(out, "slices"))

    levels = []
    for lv in index["levels"]:
        src = os.path.join(mesh_dir, lv["obj_file"])
        digest = sha256_file(src)
        if digest != lv["obj_sha256"]:
            raise SystemExit(f"{src}: sha256 {digest} != {lv['obj_sha256']} recorded by the frontier run")
        shutil.copyfile(src, os.path.join(out, "meshes", lv["obj_file"]))
        levels.append({**lv})

    with open(args.dataset_manifest, "rb") as fh:
        dm = json.loads(fh.read().decode("utf-8-sig"))
    case = next(c for c in dm["cases"] if c["case_id"] == args.case_id)
    mask_path = os.path.join(args.data_root, *case["mask"]["path_relative"].split("/"))
    mask, spacing, origin, _header = load_mask(mask_path)
    if list(mask.shape) != index["shape_xyz"]:
        raise SystemExit("mask shape differs from the mesh index")

    targets, target_rule = choose_targets(mask, spacing, origin)

    fg = np.argwhere(mask > 0)
    lo, hi = fg.min(0), fg.max(0)
    size = int(max(hi[0] - lo[0] + 1, hi[1] - lo[1] + 1) + 2 * SLICE_MARGIN)
    cx, cy = (lo[0] + hi[0] + 1) // 2, (lo[1] + hi[1] + 1) // 2
    x0, y0 = int(cx - size // 2), int(cy - size // 2)
    nz = mask.shape[2]
    for z in range(nz):
        img = np.zeros((size, size), dtype=np.uint8)
        xs = np.arange(x0, x0 + size)
        ys = np.arange(y0, y0 + size)
        okx = (xs >= 0) & (xs < mask.shape[0])
        oky = (ys >= 0) & (ys < mask.shape[1])
        sub = mask[np.ix_(xs[okx], ys[oky], [z])][:, :, 0]          # [x, y]
        block = np.where(sub > 0, 235, 28).astype(np.uint8).T       # rows = y (DR-008a), cols = x
        img[np.ix_(np.nonzero(oky)[0], np.nonzero(okx)[0])] = block
        png_gray(os.path.join(out, "slices", f"slice_{z:03d}.png"), img)

    bundle = bundle_js(BUNDLE_SOURCES)
    with open(os.path.join(out, "s1_bundle.js"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(bundle)
    shutil.copyfile(os.path.join(HERE, "index.html"), os.path.join(out, "index.html"))
    node = shutil.which("node")
    if node:
        check = subprocess.run([node, "--check", os.path.join(out, "s1_bundle.js")],
                               capture_output=True, text=True)
        if check.returncode != 0:
            raise SystemExit(f"s1_bundle.js does not parse:\n{check.stderr}")

    commit = subprocess.run(["git", "-C", REPO, "rev-parse", "HEAD"], capture_output=True,
                            text=True).stdout.strip()
    manifest = {
        "record": "spike_b_s1_assets",
        "schema_version": 1,
        "build_id": None,                               # filled below from the file hashes
        "case_id": args.case_id,
        "source_commit": commit,
        "staged_at": dt.datetime.now(dt.timezone(dt.timedelta(hours=7))).isoformat(timespec="seconds"),
        "geometry": {"shape_xyz": index["shape_xyz"], "spacing_xyz_mm": index["spacing_xyz_mm"],
                     "origin_world_mm": index["origin_world_mm"],
                     "geometry_contract_version": index["geometry_contract_version"],
                     "units_note": "QA-002: header default affine - voxel units, not validated mm"},
        "levels": levels,
        "targets": targets,
        "target_rule": target_rule,
        "slices": {"count": nz, "pattern": "slices/slice_{z:03d}.png", "crop_x0": x0, "crop_y0": y0,
                   "size_px": size, "content": "mask only (foreground 235, background 28); no MRI pixels",
                   "orientation": "image row = y (down), column = x (right) - DR-008a"},
    }
    files = {}
    for dirpath, _dirs, names in os.walk(out):
        for name in sorted(names):
            p = os.path.join(dirpath, name)
            files[os.path.relpath(p, out).replace(os.sep, "/")] = sha256_file(p)
    build_id = hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()[:16]
    manifest["build_id"] = build_id
    with open(os.path.join(out, "s1_manifest.json"), "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, indent=1)
        fh.write("\n")
    files["s1_manifest.json"] = sha256_file(os.path.join(out, "s1_manifest.json"))
    record = {"build_id": build_id, "source_commit": commit, "case_id": args.case_id,
              "levels": [{k: lv[k] for k in ("level", "cluster_cell_voxels", "triangle_count",
                                             "obj_file", "obj_sha256")} for lv in levels],
              "targets": len(targets), "slices": nz, "files": files}
    with open(os.path.join(os.path.dirname(out), "stage_record.json"), "w", encoding="utf-8",
              newline="\n") as fh:
        json.dump(record, fh, indent=1)
        fh.write("\n")

    with open(os.path.join(DEFAULT_ASSET_ROOT, "LATEST.txt"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(out + "\n")
    print(f"staged {out}")
    print(f"  build_id {build_id}  levels {[lv['level'] for lv in levels]}  targets {len(targets)}  "
          f"slices {nz} ({size}px crop at x0={x0}, y0={y0})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
